FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY drizzle ./drizzle
COPY tsconfig.json drizzle.config.ts ./
COPY src ./src

CMD ["sh", "-c", "if [ \"$SEED_DATA\" = \"true\" ]; then npm run db:seed; fi"]
